=== Bharanij27/Presidio-Training/invoices.dtd
<!ELEMENT invoice (items)>
<!ELEMENT items (item)*>
<!ELEMENT item (description, price, qty)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT qty (#PCDATA)>

<!ATTLIST invoice invno CDATA #REQUIRED>
<!ATTLIST item id CDATA #REQUIRED>

<!---
*  - o or many
+ - 1 or many
? 0 or 1


-->

=== Bharanij27/Presidio-Training/Invoices.xml
<!DOCTYPE invoice SYSTEM "invoices.dtd">
<invoice invno="1010a">
	<items>
		<item id="a001">
			<description>daal</description>
			<price>12</price>
			<qty>2</qty>
		</item>
		<item id="a002">
			<description>daal</description>
			<price>12</price>
			<qty>2</qty>
		</item>
	</items>
</invoice>
